### ISSUE TITLE
Usability Testing - Show error message/disable button when input is empty

### ISSUE THREAD

**Issue by Cha195** [GDGVIT/keats-android#17]
When trying to create a club, "500 Internal server error" is shown when the `continue` button is clicked without uploading a book or when a name is not given to the club.

**To Reproduce**
1. Go to create a club page.
2. Click continue without typing the name of the club or without uploading a book 

Can show an error message in a modal or disable the continue button when the input is empty.

![image](https://user-images.githubusercontent.com/60818157/127318547-33e6c20a-b30f-48a0-a54e-e7508d0817c2.png)

#### Is this is a critical security vulnerability?
- [ ] Yes: Please read code-of-conduct once
- [x] No

**Comment by mdhishaamakhtar** [comment]
Fixed in #15
