### ISSUE TITLE
Login page not finished after OTP Verification

### ISSUE THREAD

**Issue by rishavnaskar** [GDGVIT/keats-android#20]
**Describe the bug**
Once the user verifies mobile successfully and navigates to the home page, login page should not be kept in the stack, it must be finished.

**Expected behavior**
Login Page must be finished after navigation to Home Page

**Environment**
Redmi Note 5 pro (whyred) running with Pixel Experience Plus (Android 11).

**Possible solution**
try using finishAffinity() instead of just finish()

**Comment by mdhishaamakhtar** [comment]
Fixed in latest commit in #15
