### ISSUE TITLE
Usability testing - Chat page bugs

### ISSUE THREAD

**Issue by Cha195** [GDGVIT/keats-android#21]
Errors in the chat page. The club name overlaps on the chat space. Like to double-tap has no limit. Also, like increases on single continuous tap.

1. Navigate to the chat page of a club.
2. Double-tap on the message.

**Expected behavior**
The chat space should have a margin.
_Like_ should be limited to one per user per message.
Can show the likes to all the messages.

**Environment**
Android app

**Possible solution**
Restrict the number of likes to 0/1.

**Additional context**
The highlight of the heart doesn't glow at times.

![WhatsApp Image 2021-07-28 at 5 44 39 PM](https://user-images.githubusercontent.com/60818157/127320484-33449f87-550b-48b9-94a7-147f9006b59f.jpeg)

#### Is this is a critical security vulnerability?
- [ ] Yes: Please read code-of-conduct once
- [x] No

**Comment by mdhishaamakhtar** [comment]
This is expected behaviour
